### ISSUE TITLE
Email transform is wrong

### ISSUE THREAD

**Issue by PinguTS** [leebenson/conform#12]
The conformatiy for email is wrong as just does an lower(). Because the email addresses EXAMPLE@example.org, Example@example.org, and example@example.org are three different email address according to the RFC and as implemented by many email servers. While case in the domain part does not matter, case in the name part does matter. Also spaces and all weired stuff is allowed if it is escaped or quoted.

**Comment by maclav3** [comment]
https://github.com/leebenson/conform/pull/13 there you go
