### ISSUE TITLE
Custom sanitizers

### ISSUE THREAD

**Issue by gislik** [leebenson/conform#16]
Have you any intention of providing the user to register a custom sanitizers with a tag name?

The sanitizers are simple functions with the signature:
~~~go
func(string) string
~~~
Users could instantiate an object of Conform, with setters for an object which could be referred to in transformString.

If this does not go against the ethos of conform, I might be able to send a PR.

**Comment by leebenson** [comment]
@gislik - great idea. Would be happy to accept a PR.
