### ISSUE TITLE
support for string array

### ISSUE THREAD

**Issue by mh-cbon** [leebenson/conform#2]
Hi,

Look likes conform won t apply on array of strings, unless i did wrong.

```go
type NewInput struct {
    Tags        []string `form:"tags[]" validate:"dive,min=1" conform:"trim"`
}
func (e EndPoints) HandleForm(c *gin.Context) {

  var input NewInput

  c.Bind(&input)

  conform.Strings(&input)

  fmt.Printf("%q\n", input)
  fmt.Printf("%q\n", input.Tags)
}
```

```sh
curl -D - -d "tags[]=1&tags[]=  " http://localhost:8080/form
```

yields

```sh
{["1" "  "]}
["1" "  "]
```

Anyways to make that happen ?

**Comment by leebenson** [comment]
You're right - there's currently no recursion logic, so arrays are ignored. It should be a relatively simple addition to detect an array and loop through it.

I'm not currently maintaining the project but I'd happily accept a PR. There's also some work that needs to be done with Go 1.6 to properly handle reflection that is currently causing failing tests.

**Comment by mh-cbon** [comment]
well, maybe the first step is to add a travis file. Just to that on go up to 1.7 and tip. Them, given my understanding of the code it should be to had to apply recursive call when a slice is encountered.

Any reason to not maintaining it ? Is there any other alternatives i should look to ?

thanks @leebenson

**Comment by leebenson** [comment]
Just lack of time. I wrote this lib for a project last year, and no longer use it. I'm sure I'll come back to it in the future. In the meantime, I'm happy for someone to submit a PR (with a travis build file, patch for Go 1.6 and any new feature) and I'll gladly accept.
