### ISSUE TITLE
Why not initialization?

### ISSUE THREAD

**Issue by frederikhors** [leebenson/conform#28]
@gislik in https://github.com/leebenson/conform/pull/17 wrote:

> Since no object is instantiated the code is not type-safe, i.e. two thread may try to add sanitizers at the same time resulting in a corrupt state.

Can we instantiate an object?

Can we use it like:

```go
func main() {
  sanitizer := conform.New()
  conform.AddSanitizer(customOne)

  sanitizer.String(...)
}
```

Why not?

We're using dependency injection everywhere...

**Comment by leebenson** [comment]
> Why not?

This is a good idea for a feature, but not one I had in mind when I created this library.

My last personal commit was almost 5 years ago now, and I'm not actively maintaining this.

I'd happily accept a PR.

**Comment by frederikhors** [comment]
> My last personal commit was almost 5 years ago now, and I'm not actively maintaining this.

Why? Do you use something else?

**Comment by leebenson** [comment]
The same reason most people stop maintaining a library -- it no longer applies to my work.
