### ISSUE TITLE
Slice of int64 errors

### ISSUE THREAD

**Issue by nickdelja** [leebenson/conform#30]
It seems like non-string slices are trying to be conformed.  I am on version 1.2.2

```
type Test struct {
	Title      string                `json:"test" conform:"trim"`
	Statuses []int64 `json:"statuses"`
}
```

I am getting:
`reflect.Value.Convert: value of type string cannot be converted to int64`

**Comment by frederikhors** [comment]
Thi package is not maintained anymore. Can you switch and help here: https://github.com/go-playground/mold?

Thanks!

**Comment by frederikhors** [comment]
Same here. And I'm not using tags on that field. Is an embedded one.
