### ISSUE TITLE
How can I "conform" URL/URI?

### ISSUE THREAD

**Issue by alexandresgf** [leebenson/conform#5]
Hi! I'm a newbie using your helper and I didn't see any URI/URL sanitizer/normalizer in the package. So, how can I do to check if the URI/URL is correct?

Thanks!

**Comment by leebenson** [comment]
@alexandresgf - this library isn't really for "checking" correctness; it's purpose is to automatically sanitize input when a tidy-up is needed. For example, e-mail addresses that should be lowercases, name fields that should remove any extraneous whitespace, etc.

If you want to check whether a URL is correct, you could attempt to parse it using the stdlib's [Url.Parse](https://golang.org/pkg/net/url/#URL.Parse) function.
